'use strict';
const app=document.getElementById('app');
const S=window.ExamScoring;
const BANK=window.QUESTIONS;
const KEY='ifr-english-exam-v1';
const VERSION='1.1';
const TYPE={choice:'Completar con recuadros',fill:'Completar escribiendo',dictation:'Escuchar y escribir',listening:'Comprensión de audio',order:'Ordenar',match:'Relacionar',short:'Respuesta breve',correction:'Corregir',classify:'Clasificar'};
let state=null,voices=[],speech=null,view='start',noticeTimer,persisted=true;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const r=new Uint32Array(1);crypto.getRandomValues(r);const j=r[0]%(i+1);[b[i],b[j]]=[b[j],b[i]];}return b;}
function notice(t){clearTimeout(noticeTimer);document.getElementById('notice').textContent=t;noticeTimer=setTimeout(()=>document.getElementById('notice').textContent='',6000);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));persisted=true;}catch{persisted=false;notice('No fue posible guardar el avance. Mantén esta pestaña abierta y descarga el PDF al terminar.');}const e=document.getElementById('saved');if(e)e.textContent=saveMessage();}
function saveMessage(){return persisted?'Avance guardado en este navegador.':'Avance sin guardar. Mantén esta pestaña abierta.';}
function restore(){try{const s=JSON.parse(localStorage.getItem(KEY));const object=x=>x&&typeof x==='object'&&!Array.isArray(x);if(!s||s.version!==VERSION||!Array.isArray(s.ids)||s.ids.length!==45||new Set(s.ids).size!==45||!s.ids.every(id=>BANK.some(q=>q.id===id))||!Number.isInteger(s.index)||s.index<0||s.index>44||!['name','group','folio','started'].every(k=>typeof s[k]==='string'&&s[k].length)||!['answers','orderings','issues','plays'].every(k=>object(s[k]))||!['Sexto cuatrimestre','Tercer cuatrimestre'].includes(s.group)||typeof s.done!=='boolean'||(s.done&&!Number.isFinite(Date.parse(s.finished))))return;
for(const q of BANK){const a=s.answers[q.id];if(q.choices||q.tokens||q.pairs){const expected=q.choices||(q.tokens||[]).map((_,i)=>i);const original=q.pairs?q.pairs.map(p=>p[1]):expected;const order=s.orderings[q.id];if(!Array.isArray(order)||order.length!==original.length||new Set(order).size!==original.length||!order.every(v=>original.includes(v)))return;}if(a!==undefined){if(q.type==='order'){if(!Array.isArray(a)||new Set(a).size!==a.length||!a.every(i=>Number.isInteger(i)&&i>=0&&i<q.tokens.length))return;}else if(q.type==='match'||q.type==='classify'){if(!object(a)||!Object.values(a).every(v=>typeof v==='string'))return;}else if(typeof a!=='string')return;}}state=s;}catch{state=null;}}
function qs(){return state.ids.map(id=>BANK.find(q=>q.id===id));}
function answered(){return qs().filter(q=>S.complete(q,state.answers[q.id])).length;}
function stopAudio(){if('speechSynthesis' in window)window.speechSynthesis.cancel();speech=null;}
function loadVoices(){if(!('speechSynthesis' in window))return;voices=speechSynthesis.getVoices().filter(v=>/^en[-_]US$/i.test(v.lang));const select=document.getElementById('voice');if(select){const previous=select.value||state?.voice;select.innerHTML=voices.length?'<option value="">Selecciona y prueba una voz</option>'+voices.map(v=>`<option value="${esc(v.voiceURI)}">${esc(v.name)} (${esc(v.lang)})</option>`).join(''):'<option value="">No se encontró una voz estadounidense</option>';const preferred=voices.find(v=>v.voiceURI===previous)||voices.find(v=>/jenny|samantha|aria|ava|susan|zira|female|google us english|joanna|allison|salli|siri.*female/i.test(v.name));if(preferred)select.value=preferred.voiceURI;}}
function speak(text,rate=1){stopAudio();if(!('speechSynthesis' in window)){notice('Este navegador no puede reproducir la voz. Avisa al profesor.');return;}
 loadVoices();const uri=document.getElementById('voice')?.value||state?.voice;const selected=voices.find(v=>v.voiceURI===uri);
 if(!selected){notice('Selecciona y prueba una voz de inglés estadounidense. Si no aparece, avisa al profesor.');return;}
 const u=new SpeechSynthesisUtterance(text);u.lang=selected.lang;u.voice=selected;u.rate=rate;u.pitch=1;speech=u;let started=false;const timer=setTimeout(()=>{if(!started){notice('El audio no inició. Revisa el volumen o registra el problema para tu profesor.');stopAudio();}},8000);u.onstart=()=>{started=true;clearTimeout(timer);};u.onend=()=>clearTimeout(timer);u.onerror=e=>{clearTimeout(timer);if(e.error!=='canceled'&&e.error!=='interrupted')notice('No se pudo reproducir el audio. Puedes registrar el problema para revisión.');};speechSynthesis.speak(u);
}
function audioSettings(){return `<label for="voice">Voz de inglés estadounidense</label><select id="voice" aria-label="Voz de inglés estadounidense"></select><small>Preferencia: voz femenina estadounidense. El navegador no indica el género de todas las voces: escúchala y confirma la selección con tu profesor. Las voces disponibles dependen del dispositivo.</small>`;}
function startScreen(){view='start';stopAudio();app.innerHTML=`<div class="intro"><section class="card dark"><div class="eyebrow">Evaluación individual</div><h1>Lo que ya sabes<br>de inglés.</h1><p class="muted">Lee, escucha y responde. Una actividad a la vez.</p><div class="stats"><div><strong>45</strong><span>ejercicios breves</span></div><div><strong>5</strong><span>temas</span></div><div><strong>90</strong><span>min aprox.</span></div></div><ol class="topic-list">${TOPICS.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><p class="small muted">El tema 5 termina en expresiones de tiempo. No hay cronómetro ni cierre automático.</p></section><section class="card"><div class="eyebrow">Antes de comenzar</div><h2>Prepara tu evaluación</h2>${state?`<div class="summary-note">Hay ${state.done?'un resultado':'un intento'} de <strong>${esc(state.name)}</strong> en este dispositivo.<div class="row"><button class="primary" id="resume">${state.done?'Ver resultado':'Continuar intento'}</button><button id="newAttempt">Otro alumno</button></div></div>`:''}<form id="startForm"><label class="field" for="name">Nombre completo<input id="name" required maxlength="100" autocomplete="name" placeholder="Escribe tu nombre"></label><label class="field" for="group">Cuatrimestre<select id="group" required><option value="">Selecciona tu cuatrimestre</option><option value="Sexto cuatrimestre">Sexto cuatrimestre</option><option value="Tercer cuatrimestre">Tercer cuatrimestre</option></select></label><div class="audio-box">${audioSettings()}<div class="row" style="margin-top:12px"><button type="button" id="testAudio">Probar audio</button><button type="button" id="stopAudio">Detener</button></div></div><label class="check"><input type="checkbox" required id="ready"><span>Probé el audio o avisé al profesor si no funciona.</span></label><p class="small muted">Puedes cambiar tus respuestas antes de entregar. Se aceptan las contracciones válidas indicadas. Al finalizar, descarga el PDF y entrégalo a tu profesor.</p><p class="small muted">Tus datos y respuestas se conservan en este navegador; no se envían automáticamente.</p><button class="primary wide" type="submit">Comenzar evaluación</button></form></section></div>`;
 loadVoices();document.getElementById('testAudio').onclick=()=>speak('Hello. This is your English audio test.');document.getElementById('stopAudio').onclick=stopAudio;
 document.getElementById('resume')?.addEventListener('click',()=>state.done?results():renderQuestion());
 document.getElementById('newAttempt')?.addEventListener('click',()=>{if(confirm('Se borrará de este navegador el intento anterior. Descarga primero su PDF si ya está terminado. ¿Continuar?')){state=null;try{localStorage.removeItem(KEY);}catch{}startScreen();}});
 document.getElementById('startForm').onsubmit=e=>{e.preventDefault();if(state&&!confirm('Hay un intento guardado. ¿Reemplazarlo por uno nuevo?'))return;const name=document.getElementById('name').value.trim(),group=document.getElementById('group').value.trim();if(!name||!['Sexto cuatrimestre','Tercer cuatrimestre'].includes(group)){notice('Escribe tu nombre completo y selecciona tu cuatrimestre.');return;}const voice=document.getElementById('voice').value;state={version:VERSION,name,group,voice,started:new Date().toISOString(),folio:crypto.randomUUID?crypto.randomUUID().slice(0,8).toUpperCase():String(Date.now()),ids:[1,2,3,4,5].flatMap(t=>shuffle(BANK.filter(q=>q.topic===t)).map(q=>q.id)),answers:{},orderings:{},issues:{},plays:{},index:0,done:false};BANK.forEach(q=>{if(q.choices)state.orderings[q.id]=shuffle(q.choices);if(q.tokens)state.orderings[q.id]=shuffle(q.tokens.map((_,i)=>i));if(q.pairs)state.orderings[q.id]=shuffle(q.pairs.map(p=>p[1]));});save();renderQuestion();};
}
function side(){const list=qs();return `<aside class="card side"><div class="eyebrow">Tu recorrido</div><h2>Los cinco temas</h2><nav class="topic-nav" aria-label="Temas">${TOPICS.map((t,i)=>`<button class="topic-button ${list[state.index]?.topic===i+1?'active':''}" data-topic="${i+1}">${i+1}<span class="full">${esc(t)}</span><span>${list.filter(q=>q.topic===i+1&&S.complete(q,state.answers[q.id])).length}/9</span></button>`).join('')}</nav><div class="question-grid" aria-label="Ir a un ejercicio">${list.map((q,i)=>`<button title="Ejercicio ${i+1}: ${S.complete(q,state.answers[q.id])?'respondido':'pendiente'}" aria-label="Ejercicio ${i+1}, ${S.complete(q,state.answers[q.id])?'respondido':'pendiente'}" ${i===state.index?'aria-current="step"':''} data-index="${i}" class="${S.complete(q,state.answers[q.id])?'answered ':''}${i===state.index?'current':''}">${i+1}</button>`).join('')}</div><p class="small muted">Verde: respondido. Puedes regresar y revisar.</p><button class="wide" id="review">Revisar y entregar</button></aside>`;}
function bindSide(){document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>go(qs().findIndex(q=>q.topic===+b.dataset.topic)));document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>go(+b.dataset.index));document.getElementById('review').onclick=review;}
function go(i){state.index=Math.max(0,Math.min(44,i));save();renderQuestion();document.getElementById('questionTitle').focus();}
function setAnswer(q,a){state.answers[q.id]=a;save();document.getElementById('count').textContent=answered()+' de 45 respondidos';document.getElementById('progress').value=answered();const square=document.querySelector('[data-index="'+state.index+'"]');if(square){const complete=S.complete(q,a);square.classList.toggle('answered',complete);square.title='Ejercicio '+(state.index+1)+': '+(complete?'respondido':'pendiente');square.setAttribute('aria-label',square.title);}document.querySelectorAll('[data-topic]').forEach(b=>{b.lastElementChild.textContent=qs().filter(x=>x.topic===+b.dataset.topic&&S.complete(x,state.answers[x.id])).length+'/9';});}
function renderQuestion(){view='exam';stopAudio();const q=qs()[state.index],value=state.answers[q.id];let fields='';
 if(q.choices){fields=`<div class="choices">${state.orderings[q.id].map((v,i)=>`<button class="choice ${value===v?'selected':''}" aria-pressed="${value===v}" data-choice="${esc(v)}"><b>${String.fromCharCode(65+i)}</b><span lang="en">${esc(v)}</span></button>`).join('')}</div>`;}
 else if(q.type==='order'){const chosen=Array.isArray(value)?value:[];fields=`<p class="small muted">Toca los recuadros en orden. Toca una palabra de tu respuesta para quitarla.</p><div class="answer-zone tokens" aria-label="Tu orden">${chosen.length?chosen.map((n,i)=>`<button data-remove="${i}" aria-label="Quitar ${esc(q.tokens[n])}" lang="en">${esc(q.tokens[n])}</button>`).join(''):'<span class="muted">Tu respuesta aparecerá aquí.</span>'}</div><div class="tokens">${state.orderings[q.id].filter(i=>!chosen.includes(i)).map(i=>`<button data-token="${i}" lang="en">${esc(q.tokens[i])}</button>`).join('')}</div><button id="clearOrder">Borrar orden</button>`;}
 else if(q.type==='match'||q.type==='classify'){const data=q.type==='match'?q.pairs.map(p=>p[0]):q.items.map(p=>p.text);const options=q.type==='match'?state.orderings[q.id]:q.categories;fields=data.map((v,i)=>`<div class="pair"><label lang="en" for="pair-${i}">${esc(v)}</label><select id="pair-${i}" data-pair="${i}" aria-label="Respuesta para ${esc(v)}"><option value="">Selecciona…</option>${options.map(o=>`<option value="${esc(o)}" ${value?.[i]===o?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`).join('');}
 else fields=`<label class="field" for="written">Tu respuesta<textarea id="written" lang="en" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="500" placeholder="Escribe aquí…">${esc(value||'')}</textarea></label><p class="small muted">Revisa tu respuesta. No se descuentan mayúsculas ni punto final; la estructura y las palabras sí cuentan.</p>`;
 app.innerHTML=`<div class="layout">${side()}<section class="card"><div class="progress-meta"><span id="count">${answered()} de 45 respondidos</span><span>Sin límite de tiempo</span></div><progress id="progress" max="45" value="${answered()}" aria-label="Ejercicios respondidos"></progress><div class="qtop"><span>Ejercicio ${state.index+1} de 45 · Tema ${q.topic}</span><span class="type">${TYPE[q.type]}</span></div><h2 id="questionTitle" tabindex="-1">${esc(TOPICS[q.topic-1])}</h2><p class="prompt">${esc(q.prompt)}</p>${q.audio?`<div class="audio-box"><div class="row"><button id="play" class="primary">Escuchar</button><button id="slow">Escuchar lento (0.5×)</button><button id="stop">Detener</button></div><small>Puedes volver a escuchar. La frase permanece oculta durante el intento.</small><details><summary>Configurar voz</summary>${audioSettings()}</details><label class="check problem"><input type="checkbox" id="audioIssue" ${state.issues[q.id]?'checked':''}>No pude escuchar el audio; solicito revisión del profesor.</label></div>`:''}${fields}<div class="save-state" id="saved">${saveMessage()}</div><div class="nav-buttons"><button id="prev" ${state.index===0?'disabled':''}>Anterior</button><button id="next" class="primary">${state.index===44?'Revisar y entregar':'Siguiente'}</button></div></section></div>`;
 bindSide();document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{setAnswer(q,b.dataset.choice);renderQuestion();});document.getElementById('written')?.addEventListener('input',e=>setAnswer(q,e.target.value));document.querySelectorAll('[data-pair]').forEach(s=>s.onchange=()=>setAnswer(q,{...(state.answers[q.id]||{}),[s.dataset.pair]:s.value}));document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{setAnswer(q,[...(state.answers[q.id]||[]),+b.dataset.token]);renderQuestion();});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const a=[...(state.answers[q.id]||[])];a.splice(+b.dataset.remove,1);setAnswer(q,a);renderQuestion();});document.getElementById('clearOrder')?.addEventListener('click',()=>{setAnswer(q,[]);renderQuestion();});
 if(q.audio){loadVoices();document.getElementById('voice').onchange=e=>{state.voice=e.target.value;save();};const play=rate=>{state.plays[q.id]=(state.plays[q.id]||0)+1;save();speak(q.audio,rate);};document.getElementById('play').onclick=()=>play(1);document.getElementById('slow').onclick=()=>play(.5);document.getElementById('stop').onclick=stopAudio;document.getElementById('audioIssue').onchange=e=>{state.issues[q.id]=e.target.checked;save();};}
 document.getElementById('prev').onclick=()=>go(state.index-1);document.getElementById('next').onclick=()=>state.index===44?review():go(state.index+1);
}
function review(){view='review';stopAudio();const pending=45-answered();app.innerHTML=`<section class="card"><div class="eyebrow">Antes de entregar</div><h1>Revisa tu evaluación</h1><p><strong>${esc(state.name)}</strong> · ${esc(state.group)}</p><p>${answered()} ejercicios respondidos y ${pending} pendientes.</p>${pending?'<div class="summary-note">Los ejercicios sin respuesta reciben cero puntos, salvo los audios reportados, que quedan pendientes de revisión docente.</div>':''}<div class="summary-list">${qs().map((q,i)=>`<div class="summary-item"><span>${i+1}. ${TYPE[q.type]} · Tema ${q.topic}<br><small>${state.issues[q.id]?'Audio reportado':S.complete(q,state.answers[q.id])?'Respondido':'Pendiente'}</small></span><button data-index="${i}">Revisar</button></div>`).join('')}</div><div class="nav-buttons"><button id="back">Seguir respondiendo</button><button id="finish" class="primary">Entregar y ver resultado</button></div><p class="small muted">Al entregar se cierran las respuestas de este intento. Después podrás descargar tu PDF.</p></section>`;document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>go(+b.dataset.index));document.getElementById('back').onclick=renderQuestion;document.getElementById('finish').onclick=()=>{if(!confirm(`Entregar con ${pending} ejercicios pendientes. Después no podrás modificar este intento. ¿Continuar?`))return;state.done=true;state.finished=new Date().toISOString();save();results();};}
function totals(){let points=0,review=0;const topics=TOPICS.map(()=>({score:0,pending:0}));qs().forEach(q=>{if(q.audio&&state.issues[q.id]){review++;topics[q.topic-1].pending++;}else{const p=S.grade(q,state.answers[q.id]);points+=p;topics[q.topic-1].score+=p;}});return {points,review,topics,grade:points/45*10};}
function resultDetails(){return qs().map((q,i)=>{const p=S.grade(q,state.answers[q.id]),pending=q.audio&&state.issues[q.id];return `<details class="review"><summary>${i+1}. Tema ${q.topic} · ${TYPE[q.type]} · <span class="${p===1?'ok':'wrong'}">${pending?'Por revisar':p.toLocaleString('es-MX',{maximumFractionDigits:2})+' / 1'}</span></summary><p>${esc(q.prompt)}</p>${q.audio?`<p><strong>Audio:</strong> ${esc(q.audio)}</p>`:''}<p><strong>Tu respuesta:</strong> ${esc(S.answerText(q,state.answers[q.id]))}</p><p><strong>Respuesta prevista:</strong> ${esc(S.expected(q))}</p><p>${esc(q.explain)}</p></details>`;}).join('');}
function results(){view='results';stopAudio();const t=totals();app.innerHTML=`<section class="card"><div class="eyebrow">Evaluación entregada</div><h1>Tu resultado</h1><p><strong>${esc(state.name)}</strong> · ${esc(state.group)} · Folio ${esc(state.folio)}</p><div class="results-score">${t.grade.toFixed(2)} <small>/ 10 ${t.review?'provisional':''}</small></div><p>${t.points.toFixed(2)} de 45 puntos${t.review?` · ${t.review} ejercicios pendientes por problemas de audio`:''}.</p>${t.review?'<div class="summary-note">La nota es provisional. Los ejercicios de audio reportados no tienen calificación asignada; el profesor debe revisarlos antes de cerrar tu resultado.</div>':''}<div class="results-grid">${t.topics.map((x,i)=>`<div class="result-tile"><span>Tema ${i+1}</span><strong>${x.score.toFixed(2)} / 9</strong><small>${esc(TOPICS[i])}${x.pending?` · ${x.pending} por revisar`:''}</small></div>`).join('')}</div><div class="row no-print"><button id="pdf" class="primary">Descargar resultado en PDF</button><button id="print">Imprimir / Guardar PDF</button></div><p class="small muted">Entrega el PDF a tu profesor. El resultado no se envía automáticamente. Conserva una copia antes de borrar este intento.</p><h2>Detalle de tus respuestas</h2>${resultDetails()}<hr><button id="restart" class="no-print">Volver al inicio</button></section>`;document.getElementById('pdf').onclick=downloadPDF;document.getElementById('print').onclick=()=>{const details=[...document.querySelectorAll('details.review')],opened=details.map(d=>d.open);details.forEach(d=>d.open=true);window.print();details.forEach((d,i)=>d.open=opened[i]);};document.getElementById('restart').onclick=startScreen;}
function downloadPDF(){if(!window.jspdf?.jsPDF){notice('No se cargó el generador PDF. Usa Imprimir / Guardar PDF.');return;}const t=totals();const doc=new jspdf.jsPDF();let y=45;function pageHeader(){doc.setFillColor(28,30,90);doc.roundedRect(12,10,186,23,4,4,'F');doc.setFillColor(44,229,30);doc.roundedRect(12,35,186,2,1,1,'F');doc.setFont('helvetica','bold');doc.setFontSize(12);doc.setTextColor(255,255,255);doc.text('IFR  |  ENGLISH ASSESSMENT',20,24);doc.setTextColor(25,30,45);}pageHeader();const clean=s=>String(s).replace(/[’‘]/g,"'").replace(/→/g,' -> ').replace(/[“”]/g,'"').replace(/…/g,'...');
 function line(text,size=11,bold=false){doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);const lines=doc.splitTextToSize(clean(text),174);for(const l of lines){if(y>276){doc.addPage();pageHeader();doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);y=45;}doc.text(l,18,y);y+=size*.45+1.5;}y+=2;}
 doc.setTextColor(28,30,90);line('IFR | Evaluación de inglés',19,true);doc.setTextColor(25,30,45);line('Nombre: '+state.name);line('Cuatrimestre: '+state.group+' | Folio: '+state.folio);line('Entrega: '+new Date(state.finished).toLocaleString('es-MX'));line('Versión: '+VERSION+' | 45 ejercicios | 5 temas');line('Calificación '+(t.review?'provisional':'')+': '+t.grade.toFixed(2)+' / 10',16,true);line('Puntos: '+t.points.toFixed(2)+' / 45');if(t.review)line(t.review+' ejercicios de audio por revisar. Nota pendiente de validación docente.',11,true);line('Desglose por tema',13,true);t.topics.forEach((x,i)=>line((i+1)+'. '+TOPICS[i]+': '+x.score.toFixed(2)+' / 9'+(x.pending?' ('+x.pending+' por revisar)':'')));line('Cada ejercicio vale 1 punto. Relacionar y clasificar otorgan crédito proporcional. La calificación es automática y está sujeta a revisión docente.',10);line('Respuestas y retroalimentación',14,true);
 qs().forEach((q,i)=>{const pending=q.audio&&state.issues[q.id];line((i+1)+'. Tema '+q.topic+' | '+TYPE[q.type]+' | '+(pending?'PENDIENTE DE REVISIÓN':S.grade(q,state.answers[q.id]).toFixed(2)+' / 1'),12,true);line(q.prompt);if(q.audio)line('Audio: '+q.audio);line('Respuesta del alumno: '+S.answerText(q,state.answers[q.id]));line('Respuesta prevista: '+S.expected(q));line('Explicación: '+q.explain,10);if(q.audio)line('Reproducciones solicitadas: '+(state.plays[q.id]||0),9);y+=4;});
 const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setFontSize(9);doc.setTextColor(90);doc.text('Evaluación elaborada por el Profesor Morales Mendoza Raul',18,286);doc.text('IFR · '+state.folio+' · Página '+i+' de '+pages,18,292);}const filename='Evaluacion_ingles_'+state.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_').slice(0,60)+'_'+state.folio+'.pdf';doc.save(filename);notice('PDF generado. Revisa tus descargas o la opción de guardar de tu navegador.');
}
restore();startScreen();if('speechSynthesis' in window)speechSynthesis.addEventListener('voiceschanged',loadVoices);window.addEventListener('pagehide',()=>{stopAudio();if(state)save();});
