'use strict';
const app=document.getElementById('app');
const S=window.ExamScoring;
const BANK=window.QUESTIONS;
const KEY='ifr-english-exam-v1';
const VERSION='1.1';
const TYPE={choice:'Completar con recuadros',fill:'Completar escribiendo',dictation:'Escuchar y escribir',listening:'Comprensión de audio',order:'Ordenar',match:'Relacionar',short:'Respuesta breve',correction:'Corregir',classify:'Clasificar'};
let state=null,voices=[],speech=null,view='start',noticeTimer,persisted=true;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const r=new Uint32Array(1);crypto.getRandomValues(r);const j=r[0]%(i+1);[b[i],b[j]]=[b[j],b[i]];}return b;}
function notice(t){clearTimeout(noticeTimer);document.getElementById('notice').textContent=t;noticeTimer=setTimeout(()=>document.getElementById('notice').textContent='',6000);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));persisted=true;}catch{persisted=false;notice('No fue posible guardar el avance. Mantén esta pestaña abierta y descarga el PDF al terminar.');}const e=document.getElementById('saved');if(e)e.textContent=saveMessage();}
function saveMessage(){return persisted?'Guardado':'Sin guardar. Mantén esta pestaña abierta.';}
function restore(){try{const s=JSON.parse(localStorage.getItem(KEY));const object=x=>x&&typeof x==='object'&&!Array.isArray(x);if(!s||s.version!==VERSION||!Array.isArray(s.ids)||s.ids.length!==45||new Set(s.ids).size!==45||!s.ids.every(id=>BANK.some(q=>q.id===id))||!Number.isInteger(s.index)||s.index<0||s.index>44||!['name','group','folio','started'].every(k=>typeof s[k]==='string'&&s[k].length)||!['answers','orderings','issues','plays'].every(k=>object(s[k]))||!['Sexto cuatrimestre','Tercer cuatrimestre'].includes(s.group)||typeof s.done!=='boolean'||(s.done&&!Number.isFinite(Date.parse(s.finished))))return;
for(const q of BANK){const a=s.answers[q.id];if(q.choices||q.tokens||q.pairs){const expected=q.choices||(q.tokens||[]).map((_,i)=>i);const original=q.pairs?q.pairs.map(p=>p[1]):expected;const order=s.orderings[q.id];if(!Array.isArray(order)||order.length!==original.length||new Set(order).size!==original.length||!order.every(v=>original.includes(v)))return;}if(a!==undefined){if(q.type==='order'){if(!Array.isArray(a)||new Set(a).size!==a.length||!a.every(i=>Number.isInteger(i)&&i>=0&&i<q.tokens.length))return;}else if(q.type==='match'||q.type==='classify'){if(!object(a)||!Object.values(a).every(v=>typeof v==='string'))return;}else if(typeof a!=='string')return;}}state=s;}catch{state=null;}}
function qs(){return state.ids.map(id=>BANK.find(q=>q.id===id));}
function answered(){return qs().filter(q=>S.complete(q,state.answers[q.id])).length;}
function stopAudio(){if('speechSynthesis' in window)window.speechSynthesis.cancel();speech=null;}
function loadVoices(){if(!('speechSynthesis' in window))return;voices=speechSynthesis.getVoices().filter(v=>/^en[-_]US$/i.test(v.lang));const select=document.getElementById('voice');if(select){const previous=select.value||state?.voice;select.innerHTML=voices.length?'<option value="">Selecciona y prueba una voz</option>'+voices.map(v=>`<option value="${esc(v.voiceURI)}">${esc(v.name)} (${esc(v.lang)})</option>`).join(''):'<option value="">No se encontró una voz estadounidense</option>';const preferred=voices.find(v=>v.voiceURI===previous)||voices.find(v=>/jenny|samantha|aria|ava|susan|zira|female|google us english|joanna|allison|salli|siri.*female/i.test(v.name));if(preferred)select.value=preferred.voiceURI;}}
function speak(text,rate=1){stopAudio();if(!('speechSynthesis' in window)){notice('Este navegador no puede reproducir la voz. Avisa al profesor.');return;}
 loadVoices();const uri=document.getElementById('voice')?.value||state?.voice;const selected=voices.find(v=>v.voiceURI===uri);
 if(!selected){notice('Selecciona y prueba una voz de inglés estadounidense. Si no aparece, avisa al profesor.');return;}
 const u=new SpeechSynthesisUtterance(text);u.lang=selected.lang;u.voice=selected;u.rate=rate;u.pitch=1;speech=u;let started=false;const timer=setTimeout(()=>{if(!started){notice('El audio no inició. Revisa el volumen o registra el problema para tu profesor.');stopAudio();}},8000);u.onstart=()=>{started=true;clearTimeout(timer);};u.onend=()=>clearTimeout(timer);u.onerror=e=>{clearTimeout(timer);if(e.error!=='canceled'&&e.error!=='interrupted')notice('No se pudo reproducir el audio. Puedes registrar el problema para revisión.');};speechSynthesis.speak(u);
}
function audioSettings(){return `<label for="voice">Voz del audio</label><select id="voice" aria-label="Voz del audio"></select>`;}
function startScreen(){view='start';stopAudio();app.innerHTML=`<div class="intro"><section class="card dark"><div class="eyebrow">Evaluación individual</div><h1>Evaluación<br>de inglés</h1><p class="muted">Responde los cinco temas.</p><div class="stats"><div><strong>45</strong><span>ejercicios breves</span></div><div><strong>5</strong><span>temas</span></div><div><strong>90</strong><span>min aprox.</span></div></div><ol class="topic-list">${TOPICS.map(t=>`<li>${esc(t)}</li>`).join('')}</ol></section><section class="card"><div class="eyebrow">Datos del alumno</div><h2>Registra tus datos</h2>${state?`<div class="summary-note">Hay ${state.done?'un resultado':'un intento'} de <strong>${esc(state.name)}</strong> en este dispositivo.<div class="row"><button class="primary" id="resume">${state.done?'Ver resultado':'Continuar intento'}</button><button id="newAttempt">Otro alumno</button></div></div>`:''}<form id="startForm"><label class="field" for="name">Nombre completo<input id="name" required maxlength="100" autocomplete="name" placeholder="Escribe tu nombre"></label><label class="field" for="group">Cuatrimestre<select id="group" required><option value="">Selecciona tu cuatrimestre</option><option value="Sexto cuatrimestre">Sexto cuatrimestre</option><option value="Tercer cuatrimestre">Tercer cuatrimestre</option></select></label><div class="audio-box">${audioSettings()}<div class="row" style="margin-top:12px"><button type="button" id="testAudio">Probar audio</button><button type="button" id="stopAudio">Detener</button></div></div><label class="check"><input type="checkbox" required id="ready"><span>Probé el audio o reporté un problema al profesor.</span></label><button class="primary wide" type="submit">Comenzar evaluación</button></form></section></div>`;
 loadVoices();document.getElementById('testAudio').onclick=()=>speak('Hello. This is your English audio test.');document.getElementById('stopAudio').onclick=stopAudio;
 document.getElementById('resume')?.addEventListener('click',()=>state.done?results():renderQuestion());
 document.getElementById('newAttempt')?.addEventListener('click',()=>{if(confirm('Se borrará de este navegador el intento anterior. Descarga primero su PDF si ya está terminado. ¿Continuar?')){state=null;try{localStorage.removeItem(KEY);}catch{}startScreen();}});
 document.getElementById('startForm').onsubmit=e=>{e.preventDefault();if(state&&!confirm('Hay un intento guardado. ¿Reemplazarlo por uno nuevo?'))return;const name=document.getElementById('name').value.trim(),group=document.getElementById('group').value.trim();if(!name||!['Sexto cuatrimestre','Tercer cuatrimestre'].includes(group)){notice('Escribe tu nombre completo y selecciona tu cuatrimestre.');return;}const voice=document.getElementById('voice').value;state={version:VERSION,name,group,voice,started:new Date().toISOString(),folio:crypto.randomUUID?crypto.randomUUID().slice(0,8).toUpperCase():String(Date.now()),ids:[1,2,3,4,5].flatMap(t=>shuffle(BANK.filter(q=>q.topic===t)).map(q=>q.id)),answers:{},orderings:{},issues:{},plays:{},index:0,done:false};BANK.forEach(q=>{if(q.choices)state.orderings[q.id]=shuffle(q.choices);if(q.tokens)state.orderings[q.id]=shuffle(q.tokens.map((_,i)=>i));if(q.pairs)state.orderings[q.id]=shuffle(q.pairs.map(p=>p[1]));});save();renderQuestion();};
}
function side(){const list=qs();return `<aside class="card side"><div class="eyebrow">Evaluación</div><h2>Los cinco temas</h2><nav class="topic-nav" aria-label="Temas">${TOPICS.map((t,i)=>`<button class="topic-button ${list[state.index]?.topic===i+1?'active':''}" data-topic="${i+1}">${i+1}<span class="full">${esc(t)}</span></button>`).join('')}</nav><details class="exercise-nav"><summary>Ir a un ejercicio</summary><div class="question-grid" aria-label="Ir a un ejercicio">${list.map((q,i)=>`<button title="Ejercicio ${i+1}" aria-label="Ejercicio ${i+1}" ${i===state.index?'aria-current="step"':''} data-index="${i}" class="${i===state.index?'current':''}">${i+1}</button>`).join('')}</div></details><button class="wide" id="review">Revisar y entregar</button></aside>`;}
function bindSide(){document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>go(qs().findIndex(q=>q.topic===+b.dataset.topic)));document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>go(+b.dataset.index));document.getElementById('review').onclick=review;}
function go(i){state.index=Math.max(0,Math.min(44,i));save();renderQuestion();document.getElementById('questionTitle').focus();}
function setAnswer(q,a){state.answers[q.id]=a;save();}
function renderQuestion(){view='exam';stopAudio();const q=qs()[state.index],value=state.answers[q.id];let fields='';
 if(q.choices){fields=`<div class="choices">${state.orderings[q.id].map((v,i)=>`<button class="choice ${value===v?'selected':''}" aria-pressed="${value===v}" data-choice="${esc(v)}"><b>${String.fromCharCode(65+i)}</b><span lang="en">${esc(v)}</span></button>`).join('')}</div>`;}
 else if(q.type==='order'){const chosen=Array.isArray(value)?value:[];fields=`<p class="small muted">Toca los recuadros en orden. Toca de nuevo para quitar.</p><div class="answer-zone tokens" aria-label="Tu orden">${chosen.length?chosen.map((n,i)=>`<button data-remove="${i}" aria-label="Quitar ${esc(q.tokens[n])}" lang="en">${esc(q.tokens[n])}</button>`).join(''):'<span class="muted">Tu respuesta aparecerá aquí.</span>'}</div><div class="tokens">${state.orderings[q.id].filter(i=>!chosen.includes(i)).map(i=>`<button data-token="${i}" lang="en">${esc(q.tokens[i])}</button>`).join('')}</div><button id="clearOrder">Borrar orden</button>`;}
 else if(q.type==='match'||q.type==='classify'){const data=q.type==='match'?q.pairs.map(p=>p[0]):q.items.map(p=>p.text);const options=q.type==='match'?state.orderings[q.id]:q.categories;fields=data.map((v,i)=>`<div class="pair"><label lang="en" for="pair-${i}">${esc(v)}</label><select id="pair-${i}" data-pair="${i}" aria-label="Respuesta para ${esc(v)}"><option value="">Selecciona…</option>${options.map(o=>`<option value="${esc(o)}" ${value?.[i]===o?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`).join('');}
 else fields=`<label class="field" for="written">Tu respuesta<textarea id="written" lang="en" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="500" placeholder="Escribe aquí…">${esc(value||'')}</textarea></label>`;
 app.innerHTML=`<div class="layout">${side()}<section class="card"><div class="qtop"><span>Ejercicio ${state.index+1} · Tema ${q.topic}</span><span class="type">${TYPE[q.type]}</span></div><h2 id="questionTitle" tabindex="-1">${esc(TOPICS[q.topic-1])}</h2><p class="prompt">${esc(q.prompt)}</p>${q.audio?`<div class="audio-box"><div class="row"><button id="play" class="primary">Escuchar</button><button id="slow">Escuchar lento (0.5×)</button><button id="stop">Detener</button></div><details><summary>Configurar voz</summary>${audioSettings()}</details><label class="check problem"><input type="checkbox" id="audioIssue" ${state.issues[q.id]?'checked':''}>No pude escuchar el audio.</label></div>`:''}${fields}<div class="save-state" id="saved">${saveMessage()}</div><div class="nav-buttons"><button id="prev" ${state.index===0?'disabled':''}>Anterior</button><button id="next" class="primary">${state.index===44?'Revisar y entregar':'Siguiente'}</button></div></section></div>`;
 bindSide();document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{setAnswer(q,b.dataset.choice);renderQuestion();});document.getElementById('written')?.addEventListener('input',e=>setAnswer(q,e.target.value));document.querySelectorAll('[data-pair]').forEach(s=>s.onchange=()=>setAnswer(q,{...(state.answers[q.id]||{}),[s.dataset.pair]:s.value}));document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{setAnswer(q,[...(state.answers[q.id]||[]),+b.dataset.token]);renderQuestion();});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const a=[...(state.answers[q.id]||[])];a.splice(+b.dataset.remove,1);setAnswer(q,a);renderQuestion();});document.getElementById('clearOrder')?.addEventListener('click',()=>{setAnswer(q,[]);renderQuestion();});
 if(q.audio){loadVoices();document.getElementById('voice').onchange=e=>{state.voice=e.target.value;save();};const play=rate=>{state.plays[q.id]=(state.plays[q.id]||0)+1;save();speak(q.audio,rate);};document.getElementById('play').onclick=()=>play(1);document.getElementById('slow').onclick=()=>play(.5);document.getElementById('stop').onclick=stopAudio;document.getElementById('audioIssue').onchange=e=>{state.issues[q.id]=e.target.checked;save();};}
 document.getElementById('prev').onclick=()=>go(state.index-1);document.getElementById('next').onclick=()=>state.index===44?review():go(state.index+1);
}
function review(){view='review';stopAudio();const pending=45-answered();app.innerHTML=`<section class="card"><div class="eyebrow">Antes de entregar</div><h1>Revisa tu evaluación</h1><p><strong>${esc(state.name)}</strong> · ${esc(state.group)}</p><p>Revisa tus respuestas y entrega la evaluación.</p>${pending?'<div class="summary-note">Las respuestas vacías valen cero. Los audios reportados quedan pendientes de revisión.</div>':''}<div class="summary-list">${qs().map((q,i)=>`<div class="summary-item"><span>${i+1}. ${TYPE[q.type]} · Tema ${q.topic}</span><button data-index="${i}">Revisar</button></div>`).join('')}</div><div class="nav-buttons"><button id="back">Seguir respondiendo</button><button id="finish" class="primary">Entregar y ver resultado</button></div><p class="small muted">Al entregar ya no podrás cambiar tus respuestas.</p></section>`;document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>go(+b.dataset.index));document.getElementById('back').onclick=renderQuestion;document.getElementById('finish').onclick=()=>{if(!confirm(`${pending?"Hay ejercicios sin completar. ":""}Al entregar ya no podrás modificar este intento. ¿Continuar?`))return;state.done=true;state.finished=new Date().toISOString();save();results();};}
function totals(){let points=0,review=0;const topics=TOPICS.map(()=>({score:0,pending:0}));qs().forEach(q=>{if(q.audio&&state.issues[q.id]){review++;topics[q.topic-1].pending++;}else{const p=S.grade(q,state.answers[q.id]);points+=p;topics[q.topic-1].score+=p;}});return {points,review,topics,grade:points/45*10,percentage:points/45*100};}
function feedback(q,value){
 const expected=q.pairs?q.pairs.map(p=>({text:p[0],answer:p[1]})):q.items?q.items.map(p=>({text:p.text,answer:p.category})):null;
 if(expected){const errors=expected.filter((p,i)=>value?.[i]!==p.answer).map(p=>{const i=expected.indexOf(p);return p.text+': '+(value?.[i]?'respondiste "'+value[i]+'"':'sin respuesta')+'; corresponde "'+p.answer+'".';});return errors.join(' ')+' '+q.explain;}
 if(!S.complete(q,value))return 'No escribiste o completaste la respuesta solicitada. '+q.explain;
 return 'Tu respuesta "'+S.answerText(q,value)+'" no coincide con las respuestas admitidas para este ejercicio. '+q.explain;
}
function resultDetails(){return qs().map((q,i)=>{const p=S.grade(q,state.answers[q.id]),pending=q.audio&&state.issues[q.id],correct=p===1,status=pending?'pending':correct?'correct':'incorrect';return `<article class="review result-${status}" aria-labelledby="result-${q.id}"><h3 id="result-${q.id}">${i+1}. Tema ${q.topic} · ${TYPE[q.type]} · ${pending?'Pendiente de revisión':correct?'Correcto':p>0?'Parcialmente correcto':'Incorrecto'}</h3><p>${esc(q.prompt)}</p>${q.audio?`<p><strong>Audio:</strong> ${esc(q.audio)}</p>`:''}<p><strong>Tu respuesta:</strong> ${esc(S.answerText(q,state.answers[q.id]))}</p>${pending?'<p>Reportaste un problema de audio. El profesor debe revisar este ejercicio antes de asignar su puntuación.</p>':`<p><strong>Puntos:</strong> ${p.toLocaleString('es-MX',{maximumFractionDigits:2})} / 1</p>${correct?'':`<p><strong>Por qué necesita corrección:</strong> ${esc(feedback(q,state.answers[q.id]))}</p><p><strong>Corrección:</strong> ${esc(S.expected(q))}</p>`}`}</article>`;}).join('');}
function results(){view='results';stopAudio();const t=totals();app.innerHTML=`<section class="card"><div class="eyebrow">Evaluación entregada</div><h1>Tu resultado</h1><p><strong>${esc(state.name)}</strong> · ${esc(state.group)} · Folio ${esc(state.folio)}</p><div class="results-score">${t.percentage.toFixed(2)}% <small>${t.review?'provisional':''}</small></div><div class="row no-print"><button id="pdf" class="primary">Descargar resultado en PDF</button><button id="print">Imprimir / Guardar PDF</button></div><p>${t.points.toFixed(2)} de 45 puntos${t.review?` · ${t.review} ejercicios pendientes por problemas de audio`:''}.</p>${t.review?'<div class="summary-note">La nota es provisional. Los ejercicios de audio reportados no tienen calificación asignada; el profesor debe revisarlos antes de cerrar tu resultado.</div>':''}<div class="results-grid">${t.topics.map((x,i)=>`<div class="result-tile"><span>Tema ${i+1}</span><strong>${x.score.toFixed(2)} / 9</strong><small>${esc(TOPICS[i])}${x.pending?` · ${x.pending} por revisar`:''}</small></div>`).join('')}</div><p class="small muted">Descarga el PDF y entrégalo a tu profesor.</p><h2>Detalle de tus respuestas</h2>${resultDetails()}<hr><button id="restart" class="no-print">Volver al inicio</button></section>`;document.getElementById('pdf').onclick=downloadPDF;document.getElementById('print').onclick=()=>window.print();document.getElementById('restart').onclick=startScreen;}
function downloadPDF(){if(!window.jspdf?.jsPDF){notice('No se cargó el generador PDF. Usa Imprimir / Guardar PDF.');return;}const t=totals();const doc=new jspdf.jsPDF();let y=45;function pageHeader(){doc.setFillColor(28,30,90);doc.roundedRect(12,10,186,23,4,4,'F');doc.setFillColor(44,229,30);doc.roundedRect(12,35,186,2,1,1,'F');doc.setFont('helvetica','bold');doc.setFontSize(12);doc.setTextColor(255,255,255);doc.text('IFR  |  ENGLISH ASSESSMENT',20,24);doc.setTextColor(25,30,45);}pageHeader();const clean=s=>String(s).replace(/[’‘]/g,"'").replace(/→/g,' -> ').replace(/[“”]/g,'"').replace(/…/g,'...');
 function line(text,size=11,bold=false){const textColor=doc.getTextColor();doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);const lines=doc.splitTextToSize(clean(text),174);for(const l of lines){if(y>276){doc.addPage();pageHeader();doc.setTextColor(textColor);doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);y=45;}doc.text(l,18,y);y+=size*.45+1.5;}y+=2;}
 doc.setTextColor(28,30,90);line('IFR | Evaluación de inglés',19,true);doc.setTextColor(25,30,45);line('Nombre: '+state.name);line('Cuatrimestre: '+state.group+' | Folio: '+state.folio);line('Entrega: '+new Date(state.finished).toLocaleString('es-MX'));line('Versión: '+VERSION+' | 45 ejercicios | 5 temas');line('Calificación '+(t.review?'provisional':'')+':',14,true);line(t.percentage.toFixed(2)+'%',30,true);line('Puntos: '+t.points.toFixed(2)+' / 45');if(t.review)line(t.review+' ejercicios de audio por revisar. Nota pendiente de validación docente.',11,true);line('Desglose por tema',13,true);t.topics.forEach((x,i)=>line((i+1)+'. '+TOPICS[i]+': '+x.score.toFixed(2)+' / 9'+(x.pending?' ('+x.pending+' por revisar)':'')));line('Cada ejercicio vale 1 punto. Relacionar y clasificar otorgan crédito proporcional. La calificación es automática y está sujeta a revisión docente.',10);line('Respuestas y retroalimentación',14,true);
 qs().forEach((q,i)=>{const pending=q.audio&&state.issues[q.id],p=S.grade(q,state.answers[q.id]);const block=[[(i+1)+'. Tema '+q.topic+' | '+TYPE[q.type]+' | '+(pending?'PENDIENTE DE REVISIÓN':p===1?'CORRECTO':p>0?'PARCIALMENTE CORRECTO':'INCORRECTO'),12,true],[q.prompt,11],[...(q.audio?['Audio: '+q.audio,11]:['',0])],['Respuesta del alumno: '+S.answerText(q,state.answers[q.id]),11],...(pending?[["Problema de audio reportado. Requiere revisión del profesor antes de asignar puntuación.",11]]:[['Puntos: '+p.toFixed(2)+' / 1',11],...(p===1?[]:[['Por qué necesita corrección: '+feedback(q,state.answers[q.id]),10],['Corrección: '+S.expected(q),11,true]])])];const height=block.reduce((sum,[text,size,bold])=>{if(!size)return sum;doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);return sum+doc.splitTextToSize(clean(text),174).length*(size*.45+1.5)+2;},4);if(y+Math.min(height,231)>276&&y>45){doc.addPage();pageHeader();y=45;}doc.setTextColor(...(pending?[100,75,15]:p===1?[8,119,74]:[180,35,40]));line((i+1)+'. Tema '+q.topic+' | '+TYPE[q.type]+' | '+(pending?'PENDIENTE DE REVISIÓN':p===1?'CORRECTO':p>0?'PARCIALMENTE CORRECTO':'INCORRECTO'),12,true);line(q.prompt);if(q.audio)line('Audio: '+q.audio);line('Respuesta del alumno: '+S.answerText(q,state.answers[q.id]));if(pending){line('Problema de audio reportado. Requiere revisión del profesor antes de asignar puntuación.');}else{line('Puntos: '+p.toFixed(2)+' / 1');if(p!==1){line('Por qué necesita corrección: '+feedback(q,state.answers[q.id]),10);line('Corrección: '+S.expected(q),11,true);}}y+=4;});
 const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setFontSize(9);doc.setTextColor(90);doc.text('Evaluación elaborada por el Profesor Morales Mendoza Raul',18,286);doc.text('IFR · '+state.folio+' · Página '+i+' de '+pages,18,292);}const filename='Evaluacion_ingles_'+state.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_').slice(0,60)+'_'+state.folio+'.pdf';doc.save(filename);notice('PDF generado. Revisa tus descargas o la opción de guardar de tu navegador.');
}
restore();startScreen();if('speechSynthesis' in window)speechSynthesis.addEventListener('voiceschanged',loadVoices);window.addEventListener('pagehide',()=>{stopAudio();if(state)save();});
