'use strict';
const app=document.getElementById('app');
const S=window.ExamScoring;
const BANK=window.QUESTIONS;
const KEY='ifr-english-exam-v1';
const VERSION='1.1';
const TYPE={choice:'Completar con recuadros',fill:'Completar escribiendo',dictation:'Escuchar y escribir',listening:'Comprensión de audio',order:'Ordenar',match:'Relacionar',short:'Respuesta breve',correction:'Corregir',classify:'Clasificar'};
let state=null,speech=null,view='start',noticeTimer,persisted=true;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const r=new Uint32Array(1);crypto.getRandomValues(r);const j=r[0]%(i+1);[b[i],b[j]]=[b[j],b[i]];}return b;}
function notice(t){clearTimeout(noticeTimer);document.getElementById('notice').textContent=t;noticeTimer=setTimeout(()=>document.getElementById('notice').textContent='',6000);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));persisted=true;}catch{persisted=false;notice('No fue posible guardar el avance. Mantén esta pestaña abierta y descarga el PDF al terminar.');}const e=document.getElementById('saved');if(e)e.textContent=saveMessage();}
function saveMessage(){return persisted?'':'Sin guardar. Mantén esta pestaña abierta.';}
function restore(){try{const s=JSON.parse(localStorage.getItem(KEY));const object=x=>x&&typeof x==='object'&&!Array.isArray(x);if(!s||s.version!==VERSION||!Array.isArray(s.ids)||s.ids.length!==45||new Set(s.ids).size!==45||!s.ids.every(id=>BANK.some(q=>q.id===id))||!Number.isInteger(s.index)||s.index<0||s.index>44||!['name','group','started'].every(k=>typeof s[k]==='string'&&s[k].length)||!['answers','orderings','issues','plays'].every(k=>object(s[k]))||!['Sexto cuatrimestre','Tercer cuatrimestre'].includes(s.group)||typeof s.done!=='boolean'||(s.done&&!Number.isFinite(Date.parse(s.finished))))return;
for(const q of BANK){const a=s.answers[q.id];if(q.choices||q.tokens||q.pairs){const expected=q.choices||(q.tokens||[]).map((_,i)=>i);const original=q.pairs?q.pairs.map(p=>p[1]):expected;const order=s.orderings[q.id];if(!Array.isArray(order)||order.length!==original.length||new Set(order).size!==original.length||!order.every(v=>original.includes(v)))s.orderings[q.id]=shuffle(original);}if(a!==undefined){if(q.type==='order'){if(!Array.isArray(a)||new Set(a).size!==a.length||!a.every(i=>Number.isInteger(i)&&i>=0&&i<q.tokens.length))return;}else if(q.type==='match'||q.type==='classify'){if(!object(a)||!Object.values(a).every(v=>typeof v==='string'))return;}else if(typeof a!=='string')return;}}for(const id of s.ids.slice(s.index)){const q=BANK.find(item=>item.id===id),a=s.answers[id];if(q.choices&&a!==undefined&&!q.choices.includes(a))delete s.answers[id];if(a&&(q.type==='match'||q.type==='classify'))for(const key of Object.keys(a)){const allowed=q.audioPairs?.[key]?.choices||(q.pairs?q.pairs.map(p=>p[1]):q.categories);if(!allowed.includes(a[key]))delete a[key];}}delete s.folio;state=s;}catch{state=null;}}
function qs(){return state.ids.map(id=>BANK.find(q=>q.id===id));}
function answered(){return qs().filter(q=>S.complete(q,state.answers[q.id])).length;}
function testAudioPlaying(active){const button=document.getElementById('testAudio');if(button)button.className=active?'is-playing':'';}
function stopAudio(){testAudioPlaying(false);if(speech){speech.pause();speech.currentTime=0;speech=null;}const status=document.getElementById('audioStatus');if(status)status.textContent='';}
function speak(id,rate=1){stopAudio();const audio=document.getElementById('examAudio');if(!audio)return;audio.src='assets/audio/'+id+'.wav'+(id==='t3-listening'?'?v=music-1':id==='t2-dictation'?'?v=three-words-1':id==='t2-listening'?'?v=school-sentence-1':id.startsWith('t2-')?'?v=sentences-1':'');audio.playbackRate=rate;audio.preservesPitch=true;speech=audio;const status=document.getElementById('audioStatus');if(status)status.textContent='';audio.onplaying=()=>{testAudioPlaying(id==='test');if(status)status.textContent='';};audio.onpause=()=>testAudioPlaying(false);audio.onwaiting=()=>testAudioPlaying(false);audio.onended=()=>{testAudioPlaying(false);if(status)status.textContent='';speech=null;};audio.onerror=()=>{testAudioPlaying(false);if(status)status.textContent='No se pudo reproducir. Avisa al profesor.';};audio.play().catch(error=>{if(error.name!=='AbortError'){testAudioPlaying(false);if(status)status.textContent='No se pudo reproducir. Toca Escuchar de nuevo.';}});}
function audioPlayer(){return '<audio id="examAudio" preload="none"></audio><span id="audioStatus" class="audio-status" role="status" aria-live="polite"></span>';}
function startScreen(){if(state)return state.done?results():state.readyToSubmit?review():renderQuestion();view='start';stopAudio();app.innerHTML=`<div class="intro"><section class="card dark"><h1>Evaluación<br>de inglés</h1><p class="muted">Responde los cinco temas.</p><div class="stats"><div><strong>45</strong><span>ejercicios breves</span></div><div><strong>5</strong><span>temas</span></div><div><strong>90</strong><span>min aprox.</span></div></div><div class="topics-content"><ul class="topic-list">${TOPICS.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><img class="exam-cat" src="assets/exam-cat.png?v=transparent-1" alt="Gatito feliz con peto azul y pulgar levantado, listo para la evaluación" width="1024" height="1536"></div></section><section class="card"><div class="eyebrow">Datos del alumno</div><h2>Registra tus datos</h2><form id="startForm"><label class="field" for="name">Nombre completo<input id="name" required maxlength="100" autocomplete="name" placeholder="Escribe tu nombre"></label><label class="field" for="group">Cuatrimestre<select id="group" required><option value="">Selecciona tu cuatrimestre</option><option value="Sexto cuatrimestre">Sexto cuatrimestre</option><option value="Tercer cuatrimestre">Tercer cuatrimestre</option></select></label><div class="audio-box">${audioPlayer()}<div class="row" style="margin-top:12px"><button type="button" id="testAudio">Probar audio</button><button type="button" id="stopAudio">Detener</button></div></div><button class="primary wide" type="submit">Iniciar prueba</button></form></section></div>`;
 document.getElementById('testAudio').onclick=()=>speak('test');document.getElementById('stopAudio').onclick=stopAudio;
 document.getElementById('startForm').onsubmit=e=>{e.preventDefault();if(state)return;const name=document.getElementById('name').value.trim(),group=document.getElementById('group').value.trim();if(!name||!['Sexto cuatrimestre','Tercer cuatrimestre'].includes(group)){notice('Escribe tu nombre completo y selecciona tu cuatrimestre.');return;}state={version:VERSION,name,group,started:new Date().toISOString(),ids:shuffle([1,2,3,4,5]).flatMap(t=>shuffle(BANK.filter(q=>q.topic===t)).map(q=>q.id)),answers:{},orderings:{},issues:{},plays:{},index:0,done:false};BANK.forEach(q=>{if(q.choices)state.orderings[q.id]=shuffle(q.choices);if(q.tokens)state.orderings[q.id]=shuffle(q.tokens.map((_,i)=>i));if(q.pairs)state.orderings[q.id]=shuffle(q.pairs.map(p=>p[1]));});save();renderQuestion();};
}
function go(i){if(!state||state.done||state.readyToSubmit||i!==state.index+1||i>44||!S.complete(qs()[state.index],state.answers[state.ids[state.index]]))return;state.index=i;save();renderQuestion();document.getElementById('questionTitle').focus();}
function setAnswer(q,a){if(!state||state.done||state.readyToSubmit||q.id!==state.ids[state.index])return;state.answers[q.id]=a;save();document.getElementById('next').disabled=!S.complete(q,a);}
function spellingChoices(q,i){const clip=q.audioPairs[i],saved=state.orderings[clip.id];if(Array.isArray(saved)&&saved.length===clip.choices.length&&new Set(saved).size===saved.length&&saved.every(x=>clip.choices.includes(x)))return saved;state.orderings[clip.id]=shuffle(clip.choices);save();return state.orderings[clip.id];}
function renderQuestion(){if(state.done)return results();if(state.readyToSubmit)return review();view='exam';stopAudio();const q=qs()[state.index],value=state.answers[q.id];let fields='';
 if(q.choices){fields=`<div class="choices">${state.orderings[q.id].map((v,i)=>`<button class="choice ${value===v?'selected':''}" aria-pressed="${value===v}" data-choice="${esc(v)}"><b>${String.fromCharCode(65+i)}</b><span lang="en">${esc(v)}</span></button>`).join('')}</div>`;}
 else if(q.type==='order'){const chosen=Array.isArray(value)?value:[];fields=`<p class="small muted">Toca los recuadros en orden. Toca de nuevo para quitar.</p><div class="answer-zone tokens" aria-label="Tu orden">${chosen.length?chosen.map((n,i)=>`<button data-remove="${i}" aria-label="Quitar ${esc(q.tokens[n])}" lang="en">${esc(q.tokens[n])}</button>`).join(''):'<span class="muted">Tu respuesta aparecerá aquí.</span>'}</div><div class="tokens">${state.orderings[q.id].filter(i=>!chosen.includes(i)).map(i=>`<button data-token="${i}" lang="en">${esc(q.tokens[i])}</button>`).join('')}</div><button id="clearOrder">Borrar orden</button>`;}
 else if(q.type==='match'||q.type==='classify'){const data=q.type==='match'?q.pairs.map(p=>p[0]):q.items.map(p=>p.text);const options=q.type==='match'?state.orderings[q.id]:q.categories;fields=data.map((v,i)=>`<div class="pair"><div><label for="pair-${i}">${esc(v)}</label>${q.audioPairs?`<div class="row spelling-controls"><button type="button" data-audio="${esc(q.audioPairs[i].id)}" data-rate="1" aria-label="Escuchar audio ${i+1}">Escuchar</button><button type="button" data-audio="${esc(q.audioPairs[i].id)}" data-rate="0.5" aria-label="Escuchar audio ${i+1} lento">Lento</button><button type="button" data-stop-audio="${esc(q.audioPairs[i].id)}" aria-label="Detener audio ${i+1}">Detener</button></div>`:''}</div><select id="pair-${i}" data-pair="${i}" aria-label="Respuesta para ${esc(v)}"><option value="">Selecciona…</option>${(q.audioPairs?spellingChoices(q,i):options).map(o=>`<option value="${esc(o)}" ${value?.[i]===o?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`).join('');}
 else fields=`<label class="field" for="written">Tu respuesta<textarea id="written" lang="en" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="500" placeholder="Escribe aquí…">${esc(value||'')}</textarea></label>`;
 app.innerHTML=`<div class="exam-flow"><section class="card"><div class="qtop"><span>Ejercicio ${state.index+1} · Tema ${q.topic}</span><span class="type">${TYPE[q.type]}</span></div><h2 id="questionTitle" tabindex="-1">${esc(TOPICS[q.topic-1])}</h2><p class="prompt">${esc(q.prompt)}</p>${q.audio?`<div class="audio-box"><div class="row"><button id="play" class="primary">Escuchar</button><button id="slow">Escuchar lento (0.5×)</button><button id="stop">Detener</button></div>${audioPlayer()}</div>`:q.audioPairs?audioPlayer():''}${fields}<div class="save-state" id="saved">${saveMessage()}</div><div class="nav-buttons"><button id="next" class="primary" ${S.complete(q,value)?'':'disabled'}>${state.index===44?'Finalizar prueba':'Siguiente'}</button></div></section></div>`;
 document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{setAnswer(q,b.dataset.choice);renderQuestion();});document.getElementById('written')?.addEventListener('input',e=>setAnswer(q,e.target.value));document.querySelectorAll('[data-pair]').forEach(s=>s.onchange=()=>setAnswer(q,{...(state.answers[q.id]||{}),[s.dataset.pair]:s.value}));document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{setAnswer(q,[...(state.answers[q.id]||[]),+b.dataset.token]);renderQuestion();});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const a=[...(state.answers[q.id]||[])];a.splice(+b.dataset.remove,1);setAnswer(q,a);renderQuestion();});document.getElementById('clearOrder')?.addEventListener('click',()=>{setAnswer(q,[]);renderQuestion();});
 if(q.audio){const play=rate=>{state.plays[q.id]=(state.plays[q.id]||0)+1;save();speak(q.id,rate);};document.getElementById('play').onclick=()=>play(1);document.getElementById('slow').onclick=()=>play(.5);document.getElementById('stop').onclick=stopAudio;}
 if(q.audioPairs){document.querySelectorAll('[data-audio]').forEach(b=>b.onclick=()=>{state.plays[q.id]=(state.plays[q.id]||0)+1;save();speak(b.dataset.audio,Number(b.dataset.rate));});document.querySelectorAll('[data-stop-audio]').forEach(b=>b.onclick=stopAudio);}
 document.getElementById('next').onclick=()=>state.index===44?review():go(state.index+1);
}
function review(){if(!state||state.done||state.index!==44||answered()!==45)return;state.readyToSubmit=true;save();view='review';stopAudio();const pending=45-answered();app.innerHTML=`<section class="card exam-flow"><div class="eyebrow">Entrega final</div><h1>Finaliza tu prueba</h1><p><strong>${esc(state.name)}</strong> · ${esc(state.group)}</p>${pending?'<div class="summary-note">Las respuestas vacías valen cero. Los audios reportados quedan pendientes de revisión.</div>':''}<p>Entrega para consultar tu resultado y descargar el PDF.</p><button id="finish" class="primary">Entregar y ver resultado</button></section>`;document.getElementById('finish').onclick=()=>{if(answered()!==45)return;state.done=true;state.finished=new Date().toISOString();save();results();};}
function totals(){let points=0,review=0;const topics=TOPICS.map(()=>({score:0,pending:0}));qs().forEach(q=>{if(q.audio&&state.issues[q.id]){review++;topics[q.topic-1].pending++;}else{const p=S.grade(q,state.answers[q.id]);points+=p;topics[q.topic-1].score+=p;}});return {points,review,topics,grade:points/45*10,percentage:points/45*100};}
function feedback(q,value){
 const expected=q.pairs?q.pairs.map(p=>({text:p[0],answer:p[1]})):q.items?q.items.map(p=>({text:p.text,answer:p.category})):null;
 if(expected){const errors=expected.filter((p,i)=>value?.[i]!==p.answer).map(p=>{const i=expected.indexOf(p);return p.text+': '+(value?.[i]?'respondiste "'+value[i]+'"':'sin respuesta')+'; corresponde "'+p.answer+'".';});return errors.join(' ')+' '+q.explain;}
 if(!S.complete(q,value))return 'No escribiste o completaste la respuesta solicitada. '+q.explain;
 return 'Tu respuesta "'+S.answerText(q,value)+'" no coincide con las respuestas admitidas para este ejercicio. '+q.explain;
}
function resultDetails(){return qs().map((q,i)=>{const value=state.answers[q.id],p=S.grade(q,value),pending=q.audio&&state.issues[q.id],correct=p===1,status=pending?'pending':correct?'correct':'incorrect';const pairs=q.pairs?q.pairs.map(x=>({label:x[0],expected:x[1]})):q.items?q.items.map(x=>({label:x.text,expected:x.category})):null;const answers=pairs?`<div class="answer-list">${pairs.map((item,j)=>`<div class="answer-item"><strong lang="en">${esc(item.label)}</strong><div class="answer-columns"><div><span class="answer-label">Tu respuesta</span><span>${esc(value?.[j]||'Sin respuesta')}</span></div>${!pending&&value?.[j]!==item.expected?`<div class="answer-fix"><span class="answer-label">Respuesta correcta</span><span>${esc(item.expected)}</span></div>`:''}</div></div>`).join('')}</div>`:`<div class="answer-columns"><div><span class="answer-label">Tu respuesta</span><span>${esc(S.answerText(q,value))}</span></div>${!pending&&!correct?`<div class="answer-fix"><span class="answer-label">Respuesta correcta</span><span>${esc(S.expected(q))}</span></div>`:''}</div>`;return `<article class="review result-${status}" aria-labelledby="result-${q.id}"><div class="review-heading"><div class="review-number">${i+1}</div><h3 id="result-${q.id}">${esc(TOPICS[q.topic-1])}</h3><span class="result-badge">${pending?'Por revisar':correct?'Correcto':p>0?'Parcial':'Incorrecto'}</span></div><p class="review-prompt">${esc(q.prompt)}</p>${answers}${pending?'<p class="review-explanation">Audio reportado para revisión del profesor.</p>':!correct?`<p class="review-explanation">${esc(q.explain)}</p>`:''}<div class="review-points">${pending?'Pendiente':p.toLocaleString('es-MX',{maximumFractionDigits:2})+' / 1 punto'}</div></article>`;}).join('');}
function results(){if(!state||!state.done||answered()!==45)return;view='results';stopAudio();const t=totals();app.innerHTML=`<section class="card"><div class="eyebrow">Evaluación entregada</div><h1>Tu resultado</h1><p><strong>${esc(state.name)}</strong> · ${esc(state.group)}</p><div class="results-score">${t.percentage.toFixed(2)}% <small>${t.review?'provisional':''}</small></div><div class="row no-print"><button id="pdf" class="primary">Descargar resultado en PDF</button><button id="restartTop">Volver a hacer la evaluación</button></div><p>${t.points.toFixed(2)} de 45 puntos${t.review?` · ${t.review} ejercicios pendientes por problemas de audio`:''}.</p>${t.review?'<div class="summary-note">La nota es provisional. Los ejercicios de audio reportados no tienen calificación asignada; el profesor debe revisarlos antes de cerrar tu resultado.</div>':''}<div class="results-grid">${t.topics.map((x,i)=>`<div class="result-tile"><span>Tema ${i+1}</span><strong>${x.score.toFixed(2)} / 9</strong><small>${esc(TOPICS[i])}${x.pending?` · ${x.pending} por revisar`:''}</small></div>`).join('')}</div><h2>Detalle de tus respuestas</h2>${resultDetails()}<div class="row no-print restart-area"><button id="restart">Volver a hacer la evaluación</button></div></section>`;document.getElementById('pdf').onclick=downloadPDF;document.getElementById('restart').onclick=restartEvaluation;document.getElementById('restartTop').onclick=restartEvaluation;}
async function downloadPDF(){
 if(!state?.done||answered()!==45)return;
 const button=document.getElementById('pdf'),restart=document.getElementById('restart'),restartTop=document.getElementById('restartTop');
 if(button?.disabled)return;
 if(!window.jspdf?.jsPDF||!window.IFRPDF){notice('No se pudo generar el PDF. Recarga e inténtalo de nuevo.');return;}
 if(button){button.disabled=true;button.textContent='Preparando PDF…';}if(restart)restart.disabled=true;if(restartTop)restartTop.disabled=true;
 try{
  const snapshot=JSON.parse(JSON.stringify(state)),questions=qs(),summary=totals();
  const assets=await IFRPDF.loadAssets();
  const doc=IFRPDF.build({jsPDF:jspdf.jsPDF,state:snapshot,questions,topics:TOPICS,scoring:S,totals:summary,assets});
  const filename='Evaluacion_ingles_'+snapshot.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_').slice(0,60)+'.pdf';
  await doc.save(filename,{returnPromise:true});
 }catch(error){console.error('PDF:',error);notice('No se pudo generar el PDF. Inténtalo de nuevo.');}
 finally{if(button){button.disabled=false;button.textContent='Descargar resultado en PDF';}if(restart)restart.disabled=false;if(restartTop)restartTop.disabled=false;}
}
function restartEvaluation(){
 if(!state?.done||answered()!==45||document.getElementById('pdf')?.disabled)return;
 try{localStorage.removeItem(KEY);}catch(error){notice('No se pudo iniciar otra evaluación. Inténtalo de nuevo.');return;}
 stopAudio();state=null;startScreen();window.scrollTo({top:0,behavior:'smooth'});
}

restore();if(state){const missing=qs().findIndex(q=>!S.complete(q,state.answers[q.id]));if(missing!==-1&&(state.done||missing<state.index)){state.done=false;delete state.finished;delete state.readyToSubmit;state.index=missing;save();}}startScreen();window.addEventListener('pagehide',()=>{stopAudio();if(state)save();});
